[toolchain]
anchor_version = "0.31.0"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agentmemory = "9dn82CtCJLpyCgFSaA1DMYL4GyGk16vhUFuRyDELNrnQ"

[programs.devnet]
agentmemory = "9dn82CtCJLpyCgFSaA1DMYL4GyGk16vhUFuRyDELNrnQ"

[programs.mainnet]
agentmemory = "9dn82CtCJLpyCgFSaA1DMYL4GyGk16vhUFuRyDELNrnQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
